train_annotation: ../datasets/annotations/trainset_highest_f1.json
test_annotation: ../datasets/annotations/testset_highest_f1.json
val_annotation: ../datasets/annotations/valset_highest_f1.json
train_val_annotation: ../datasets/annotations/trainset_valset_highest_f1.json